import { execFile } from 'child_process';
import path from 'path';
import fs from 'fs';
import os from 'os';
import { sanitizeFilename } from './security';
import { ensureYtDlpBinary, getFfmpegDir, getStandardYtDlpArgs } from './binaries';

export interface DownloadResult {
  filePath: string;
  filename: string;
  asciiFilename: string;
  contentType: string;
  fileSize: number;
  cleanup: () => Promise<void>;
}

/**
 * Downloads arbitrary media from supported source platforms using yt-dlp and ffmpeg
 */
export async function downloadMediaWithEngine(
  url: string,
  formatId: string,
  mediaType: 'video' | 'audio',
  baseTitle: string = 'media'
): Promise<DownloadResult> {
  const ytDlpPath = await ensureYtDlpBinary();
  const ffmpegDir = getFfmpegDir();

  if (!fs.existsSync(ytDlpPath)) {
    throw new Error('Media extraction engine (yt-dlp) is not installed on the server.');
  }

  const uniqueId = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const tempTemplate = path.join(os.tmpdir(), `mg_${uniqueId}_out.%(ext)s`);

  const standardArgs = getStandardYtDlpArgs(url);

  let args: string[] = [];
  let extension = 'mp4';
  let contentType = 'video/mp4';

  if (mediaType === 'audio') {
    if (formatId === 'audio_128k' || formatId === 'ig_audio_128k') {
      extension = 'm4a';
      contentType = 'audio/mp4';
      args = [
        ...standardArgs,
        '--ffmpeg-location',
        ffmpegDir,
        '-f',
        'ba[ext=m4a]/ba/18/b/best',
        '-x',
        '--audio-format',
        'm4a',
        '-o',
        tempTemplate,
        url,
      ];
    } else {
      extension = 'mp3';
      contentType = 'audio/mpeg';
      let quality = '0';
      if (formatId === 'audio_256k') quality = '2';
      if (formatId === 'audio_192k') quality = '4';

      args = [
        ...standardArgs,
        '--ffmpeg-location',
        ffmpegDir,
        '-f',
        'ba/18/b/best',
        '-x',
        '--audio-format',
        'mp3',
        '--audio-quality',
        quality,
        '-o',
        tempTemplate,
        url,
      ];
    }
  } else {
    extension = 'mp4';
    contentType = 'video/mp4';

    let height = '1080';
    if (formatId === 'video_1080p' || formatId === 'ig_video_1080p') height = '1080';
    else if (formatId === 'video_720p' || formatId === 'ig_video_720p') height = '720';
    else if (formatId === 'video_480p') height = '480';
    else if (formatId === 'video_360p') height = '360';

    const formatSelector = `bv*[height<=${height}][ext=mp4]+ba[ext=m4a]/bv*[height<=${height}]+ba/b[height<=${height}]/18/bv*+ba/b/best`;

    args = [
      ...standardArgs,
      '--ffmpeg-location',
      ffmpegDir,
      '-f',
      formatSelector,
      '--merge-output-format',
      'mp4',
      '-o',
      tempTemplate,
      url,
    ];
  }

  // Execute extraction & download with 90-second timeout
  await new Promise<void>((resolve, reject) => {
    execFile(ytDlpPath, args, { timeout: 90000 }, (error, stdout, stderr) => {
      if (error) {
        const errorOutput = stderr || stdout || error.message;
        if (errorOutput.includes('Private video') || errorOutput.includes('Video unavailable')) {
          reject(new Error('This video is unavailable or set to private by the creator on YouTube.'));
          return;
        }
        if (errorOutput.includes('Sign in to confirm your age')) {
          reject(new Error('This video is age-restricted on YouTube and requires user authentication.'));
          return;
        }
        if (errorOutput.includes('not granting access') || errorOutput.includes('empty media response') || errorOutput.includes('login-required')) {
          reject(new Error('This Instagram post or reel is private, restricted, or requires an active account login.'));
          return;
        }
        reject(new Error(`Extraction engine error: ${errorOutput.split('\n')[0]}`));
        return;
      }
      resolve();
    });
  });

  // Find generated file in temp directory
  const tmpFiles = await fs.promises.readdir(os.tmpdir());
  const matchedFile = tmpFiles.find((f) => f.startsWith(`mg_${uniqueId}_out`));

  if (!matchedFile) {
    throw new Error('Downloaded media file was not generated by extraction engine.');
  }

  const fullFilePath = path.join(os.tmpdir(), matchedFile);
  const actualExt = path.extname(matchedFile).replace('.', '') || extension;
  const stat = await fs.promises.stat(fullFilePath);

  const safeTitle = sanitizeFilename(baseTitle, 'mediagrab_media');
  const cleanAscii = safeTitle.replace(/[^\w.-]/g, '_').substring(0, 50) || 'media';
  const asciiFilename = `${cleanAscii}-${formatId}.${actualExt}`;
  const fullFilename = `${safeTitle}-${formatId}.${actualExt}`;

  // Cleanup helper
  let isCleanedUp = false;
  const cleanup = async () => {
    if (isCleanedUp) return;
    isCleanedUp = true;
    try {
      if (fs.existsSync(fullFilePath)) {
        await fs.promises.unlink(fullFilePath);
      }
    } catch {
      // Ignore cleanup error
    }
  };

  // 15-minute fallback safety timer
  setTimeout(cleanup, 15 * 60 * 1000);

  return {
    filePath: fullFilePath,
    filename: fullFilename,
    asciiFilename,
    contentType,
    fileSize: stat.size,
    cleanup,
  };
}
